[package]
name = "lockin"
version = "0.1.0"
authors = ["Matt Huszagh <huszaghmatt@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libm = "0.2.1"
iir = { path = "../iir" }
